AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: TCFJ Stats Assets

Resources:
  # Authorizer assets
  TCFJStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.tcfoodjustice.stats.StatisticsHandler
      MemorySize: 512
      Runtime: java8
      CodeUri: build/distributions/tcfj-stats.zip
      Environment:
        Variables:
          LOAD_LIMIT: 5000
          MAX_RUN_COUNT: 25
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
Outputs:
  TCFJStatsFunctionArn:
    Value: !GetAtt TCFJStatsFunction.Arn